version: "3"
services:
  kcom1:
    build: .
    ports:
      - "9080"
  kcom2:
    build: .
    ports:
      - "9080"
  kcom3:
    build: .
    ports:
      - "9080" 
  nginx:
    build:
      context: .
      dockerfile: dockerfile-nginx
    ports:
      - "9080:9080"